### ISSUE TITLE
Demo version errors when sharing a snippet

### ISSUE THREAD

**Issue by d-Rickyy-b** [kingstarfly/snippy#1]
Hi there, cool project you built :)

Sadly the demo version runs into an error when trying to share a snippet:

```
Error: Invalid `prisma.snippet.findMany()` invocation: 
Authentication failed against database server at `containers-us-west-47.railway.app`, 
the provided database credentials for `postgres` are not valid. 
Please make sure to provide valid database credentials for the database server at `containers-us-west-47.railway.app`.
```

Cheers,
Rico

**Comment by kingstarfly** [comment]
Hey Rico!

Looks like my Railway free-tier limits were reached and the Postgres database stopped working. I've changed the provider to Neon and it should work for now until the limits are reached again! ([commit](https://github.com/kingstarfly/snippy/commit/d824d642f987e8afd13fc6be28c26a8b6b71f8f1))

Please check it out again, it should be working now! 

Thanks for the support :D
